insert into institucion (idinst, nombre, direccion, telefono, imgInst, idencargado, bioseguridad, descripcion, pagina, correo, ubicacion, facebook) values (36,'Hostal Florencia', ' Manuel Mejía #120, Copacabana', ' 71963727', 'hotel36.jpg', 121, 1,'Bienvenidos a HOSTAL FLORENCIA La excelencia de sus servicios, la elegancia de su estructura y su privilegiada ubicación; a disposición de los huéspedes. Gozara con una conformidad autentica y exclusiva. Actividades Hostelería, hospedaje. Hostal en la cuidad de Copacabana, La Paz, Bolivia. Productos y servicios HOSTAL FLORENCIA dispone para su comodidad y descanso habitaciones totalmente cómodas. Habitaciones simples, dobles, triples, matrimoniales. Habitaciones ejecutivas y Suite Mirador. Centro de Convenciones “FLORENCIA” totalmente equipados con lo último en sistemas de sonido y tecnología de iluminación. Salón de Fiestas. Nuestras Habitaciones Cuentan Con: Baño Privado TV Cable Agua caliente las 24 horas Room Service Desayuno Caja de Seguridad Lavandería Garaje y parqueo interno Internet Servicio de asistencia al huésped Especialidades: Habitaciones Terrazas con vista al Lago y a toda la Cuidad de Copacabana Salón De Eventos “FLORENCIA ” con capacidad para 500 personas, totalmente equipado Salón De Eventos “FLORENCIA ” con capacidad para 150 personas, totalmente equipado Torre Ejecutiva Con Los Servicios De: Internet Cafetería Cocina Somos profesionales en el campo, con más de 11 años de experiencia en el servicio Hotelero, garantizamos el éxito de todos sus eventos y banquetes.', NULL,'florenciahostal@gmail.com', 'https://www.google.com/maps/dir/?api=1&destination=-16.167372128709%2C-69.085839986801&fbclid=IwAR1Dw8YAP8YPD58vAvJJS0BidLnMoA2PHTtIE7tteUyLqb7wz0OiuiajOs0','https://www.facebook.com/Hostal-Florencia-Bolivia-150481491784953'), (37,'Hostal Inti-wayra Isla del sol', ' Comunidad Yumani', ' 
71942015', 'hotel37.jpg', 122, 1,'El Hostal Inti Wayra está situado en Comunidad Yumani y ofrece jardín. El alojamiento ofrece servicio de habitaciones y conexión WiFi gratuita. Todas las habitaciones de la posada tienen patio con vistas al lago. También incluyen escritorio.',NULL,NULL, 'https://www.google.com/maps/place/Inti+Wayra+Hostal/@-16.0376583,-69.1473793,15z/data=!4m8!3m7!1s0x0:0x11b6aec80134df35!5m2!4m1!1i2!8m2!3d-16.0376583!4d-69.1473793','https://www.facebook.com/Hostal-Inti-wayra-Isla-del-sol-517467275254054'), (38,'Ecolodge La Estancia', ' Lago Titicaca 20 min Puerto Yumani, Isla del Sol 5912 Bolivia', ' 71596168', 'hotel38.jpg', 123, 1,'Construido sobre los principios del turismo sostenible; Ecolodge La Estancia es un albergue ecológico ubicado en la Isla del Sol. Nos esforzamos por generar el menor impacto ambiental posible y proveemos oportunidades de trabajo en las comunidades.
Información general:
Ubicado en la parte sur de la Isla del Sol de Bolivia, Ecolodge “La Estancia” es un albergue ecológico construido en 1999 con la idea de combinar el confort moderno con el estilo arquitectónico tradicional. Haciendo énfasis en la protección y preservación del medio ambiente, las cabañas de adobe están construidas sobre terrazas agrícolas preincaicas restauradas (tacanas), conservando así la armonía del paisaje circundante. Al ser un albergue ecológico, cuidamos nuestros recursos a lo largo de nuestra cadena productiva. Por ejemplo, usamos energía solar para calentar el agua y también para mantener una temperatura agradable en las habitaciones. También reutilizamos nuestras aguas residuales, con las que regamos nuestros jardines plantas nativas.', 'http://www.ecolodge-laketiticaca.com/', 'info@ecolodge-laketiticaca.com', 'https://www.google.com/maps/dir/-16.489354,-68.1526323/-16.0289396,-69.1499142/@-16.2585152,-69.2117351,9z/data=!3m1!4b1!4m4!4m3!1m1!4e1!1m0','https://www.facebook.com/EcolodgeLaEstancia'), (39,'Posada del Inca Eco-Lodge', ' Comunidad Yumani, Isla del Sol', '69965565', 'hotel39.jpg', 124, 1,'La encantadora “Posada del Inca”, está situada en la cima de la Isla del Sol, rodeada de un paisaje bucólico y la majestuosidad de los picos nevados de Los Andes. Es uno de los pocos lugares en el mundo donde aún se puede disfrutar la autenticidad de una naturaleza intacta. Esta casa de hacienda restaurada tiene 20 habitaciones con modernas instalaciones: frazadas eléctricas, baño privado, agua caliente, calefacción individual, restaurante y una vista espectacular del Lago Titicaca. Disfrute de una cálida y acogedora atmósfera, frente a los danzantes llamas de la chimenea en el lounge y bar. Este paraíso- perdido en el tiempo y en el espacio-, es accesible a través de nuestros cruceros de Hydrofoils.', 'https://www.posadadelinca.com/contact', 'info@titicaca.com', 'https://www.google.com/maps/dir/?api=1&destination=-16.036824976588%2C-69.146055377375&fbclid=IwAR1Dw8YAP8YPD58vAvJJS0BidLnMoA2PHTtIE7tteUyLqb7wz0OiuiajOs0','https://www.facebook.com/posadadelinca'), (40,'Hotel Wendy Mar', ' Avenida 16 de Julio s/n, Copacabana Bolivia', '76597886', 'hotel40.jpg', 125, 1,'Nuestro hotel al servicio de usted, tiene habitaciones con vista al lago Titicaca, disponemos de habitaciones Matrimoniales, Dobles, tríples y cuádruples, todas con baño privado y servicio de Wi Fi, incluye el desayuno buffet, estamos hubicados a cudra y media de la parada de bueses (Av. 16 de julio)', 'http://www.hotelwendymar.com.bo/', 'reservashotelwendymar19@gmail.com', 'https://www.google.com/maps/place/Hotel+Wendy+Mar/@-16.1673859,-69.088306,15z/data=!4m2!3m1!1s0x0:0xfa89dfa7a4619a62?sa=X&ved=2ahUKEwinuZ3nksftAhWtLLkGHcxrDdAQ_BIwC3oECBYQBQ','https://www.facebook.com/Hotel-Wendy-Mar-Copacabana-118484406258535')




















